import { zodResolver } from "@hookform/resolvers/zod"
import { signIn } from "next-auth/react"
import Head from "next/head"
import Link from "next/link"
import { useRouter } from "next/router"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { MyErrorMessages } from "~/components/my-error-message"

const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8).max(50)
})

type LoginFormValues = z.infer<typeof loginSchema>

export default function Login() {
  const router = useRouter()

  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema)
  })

  const onSubmit = async (data: LoginFormValues) => {
    const response = await signIn("credentials", {
      email: data.email,
      password: data.password,
      redirect: false
    })

    if (response?.ok) {
      await router.push("/dashboard")
    }
  }

  console.log(errors)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-full place-items-center">
      <form className="flex flex-col items-center gap-4 justify-center" onSubmit={handleSubmit(onSubmit)}>
          <input type="text" placeholder="email" className="input input-bordered w-full max-w-xs" {...register("email")}/>
          <MyErrorMessages errors={errors} name={"email"} />

          <input
            placeholder="password"
            type="password"
            className="input input-bordered w-full max-w-xs"
            {...register("password")}
          />

          <MyErrorMessages errors={errors} name={"password"} />

          <MyErrorMessages errors={errors} name={"passwordConfirmation"} />

          <button type="submit" className="btn btn-outline btn-primary">LogIn</button>
        </form>
        <Link href="/">Create an account</Link>
      </main>
    </>
  )
}
