import { zodResolver } from "@hookform/resolvers/zod"
import { signIn } from "next-auth/react"
import Head from "next/head"
import Link from "next/link"
import { useRouter } from "next/router"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { Button } from "~/components/ui/button"

const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8).max(50)
})

type LoginFormValues = z.infer<typeof loginSchema>

export default function Login() {
  const router = useRouter()

  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema)
  })

  const onSubmit = async (data: LoginFormValues) => {
    const response = await signIn("credentials", {
      email: data.email,
      password: data.password,
      redirect: false
    })

    if (response?.ok) {
      await router.push("/dashboard")
    }
  }

  console.log(errors)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-full place-items-center">
        <form className="" onSubmit={handleSubmit(onSubmit)}>
          <input placeholder="email" type="text" {...register("email")} />

          <input
            placeholder="password"
            type="password"
            {...register("password")}
          />

          <Button>sign up</Button>
        </form>
        <Link href="/">Create an account</Link>
      </main>
    </>
  )
}
