import { signOut } from "next-auth/react"
import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect } from "react"
import { api } from "~/utils/api"

export default function Dashboard() {
  const router = useRouter()

  const { data: users, status } = api.user.readAll.useQuery()

  useEffect(() => {
    console.log(status)
    console.log(users)
  }, [status])

  const handleSignOut = async () => {
    await signOut({ redirect: false })

    await router.push("/")
  }

  return (
    <>
      <Head>
        <title>Section1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className="btn btn-accent btn-active" onClick={handleSignOut}>
        Log out
      </button>
      <main className="flex h-full w-full items-center justify-center gap-4">
        <form action="">


          <div id="section1" className="flex w-full max-w-prose flex-col gap-3">
            <h1>Basics</h1>

            <input
              type="text"
              placeholder="first name"
              className="rounded-sm px-2 py-1"
            />
            <input
              type="text"
              placeholder="last name"
              className="rounded-sm px-2 py-1"
            />
            <input
              type="text"
              placeholder="email"
              className="rounded-sm px-2 py-1"
            />
            <input
              type="text"
              placeholder="phone numbah"
              className="rounded-sm px-2 py-1"
            />
            <input
              type="text"
              placeholder="address line"
              className="rounded-sm px-2 py-1"
            />
            <input
              type="text"
              placeholder="desired job title"
              className="rounded-sm px-2 py-1"
            />
            <textarea
              name=""
              id=""
              placeholder="descip"
              className="rounded-sm px-2 py-1"
            ></textarea>
          </div>
          <div id="section2" className="flex w-full max-w-prose flex-col gap-3">
            <h1>SkillztoKillz</h1>

            <textarea
              placeholder="list ur skills"
              className="rounded-sm px-2 py-1"
            />

          </div>
          <div id="section3" className="flex w-full max-w-prose flex-col gap-3">
            <h1>Education</h1>

            <input
              type="text"
              placeholder="school"
              className="rounded-sm px-2 py-1"
            />
            <input
              type="text"
              placeholder="years"
              className="rounded-sm px-2 py-1"
            />
            <input
              type="text"
              placeholder="degree"
              className="rounded-sm px-2 py-1"
            />
            <input
              type="text"
              placeholder="focus/major"
              className="rounded-sm px-2 py-1"
            />
            <textarea
              placeholder="additional information"
              className="rounded-sm px-2 py-1"
            />

            <button className="btn btn-primary btn-active">Submit</button>
          </div>
        </form>
      </main>
    </>
  )
}
