import { signOut } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { api } from "~/utils/api";

export default function Dashboard() {
  const router = useRouter();

  const { data: users, status } = api.user.readAll.useQuery();

  useEffect(() => {
    console.log(status);
    console.log(users);
  }, [status]);

  const handleSignOut = async () => {
    await signOut({ redirect: false });

    await router.push("/");
  };

  return (
    <>
      <Head>
        <title>Section1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className="btn btn-active btn-accent" onClick={handleSignOut}>Log out</button>
      <main className="flex h-full w-full items-center justify-center">
        <form action="" className="flex w-full max-w-prose flex-col gap-3">
          <h3>Section1</h3>

          <input
            type="text"
            placeholder="first name"
            className="rounded-sm px-2 py-1"
          />
          <input
            type="text"
            placeholder="last name"
            className="rounded-sm px-2 py-1"
          />
          <input
            type="text"
            placeholder="job title"
            className="rounded-sm px-2 py-1"
          />
          <textarea
            name=""
            id=""
            placeholder="descip"
            className="rounded-sm px-2 py-1"
          ></textarea>

          <button className="btn btn-active btn-primary">Next</button>
        </form>
      </main>
    </>
  );
}
