import { signIn } from "next-auth/react"
import Head from "next/head"
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { z } from "zod"
import { api } from "~/utils/api"
import { useRouter } from "next/router"
import Link from "next/link"
import { MyErrorMessage } from "~/components/my-error-message"
import { Button } from "~/components/ui/button"
import { Input } from "~/components/ui/input"
import { Form } from "~/components/ui/form"
import { DownloadPdfSchema, downloadPdfSchema } from "~/server/db/crud-schema"

const signUpSchema = z
  .object({
    email: z.string().email().max(255),
    password: z.string().min(8).max(50),
    passwordConfirmation: z.string().min(8).max(50)
  })
  .refine((data) => data.passwordConfirmation === data.password, {
    message: "Passwords don't match",
    path: ["passwordConfirmation"]
  })

type SignUpFormValues = z.infer<typeof signUpSchema>

export default function Home() {
  const router = useRouter()

  const {
    register,
    handleSubmit,
    formState: { errors },
    setError
  } = useForm<SignUpFormValues>({
    resolver: zodResolver(signUpSchema)
  })

  const { mutate } = api.user.create.useMutation({
    onSuccess: async (_, { password, email }) => {
      const response = await signIn("credentials", {
        email,
        password,
        redirect: false
      })

      if (response?.ok) {
        await router.push("/onboarding/step1")
      }
    },
    onError: (error) => {
      setError("email", {
        message: error.message
      })
    }
  })

  const onSubmit = (data: SignUpFormValues) => {
    mutate(data)
  }

  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Landing />
      </main>
    </>
  )
}

{
  /* <main className="flex min-h-screen flex-col items-center justify-center gap-10">
        <form
          className="flex flex-col items-center justify-center gap-4"
          onSubmit={handleSubmit(onSubmit)}
        >
          <input
            type="text"
            placeholder="email"
            className="input input-bordered w-full max-w-xs"
            {...register("email")}
          />
          <MyErrorMessage errors={errors} name={"email"} />

          <input
            placeholder="password"
            type="password"
            className="input input-bordered w-full max-w-xs"
            {...register("password")}
          />

          <MyErrorMessage errors={errors} name={"password"} />

          <input
            placeholder="confirm password"
            type="password"
            className="input input-bordered w-full max-w-xs"
            {...register("passwordConfirmation")}
          />

          <MyErrorMessage errors={errors} name={"passwordConfirmation"} />

          <button type="submit" className="btn btn-primary btn-outline">
            Sign Up
          </button>
        </form>
        <Link href="/login">Login</Link>
      </main> */
}

/**
 * v0 by Vercel.
 * @see https://v0.dev/t/IZXWYtd8zBO
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

function Landing() {
  return (
    <div className="w-full bg-gray-50">
      <section className="w-full py-12 md:py-16 xl:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Build a resume that stands out
                </h1>
                <p className="max-w-[500px] text-gray-500 dark:text-gray-400">
                  Create a professional resume in minutes with our easy-to-use
                  builder. Stand out to employers with a polished and
                  well-designed CV.
                </p>
              </div>
              <div className="flex flex-col gap-2">
                <Button variant="outline">Get Started</Button>
                <p className="text-xs text-gray-500">
                  No credit card required. 14-day free trial.
                </p>
              </div>
            </div>
            <div className="flex justify-center">
              <img
                alt="Hero"
                className="aspect-[4/3] overflow-hidden rounded-xl object-cover object-center"
                height="400"
                src="/placeholder.svg"
                width="600"
              />
            </div>
          </div>
        </div>
      </section>
      <GenerateResumeForm />

      <section className="w-full py-12 md:py-16 xl:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:items-center lg:gap-12">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Testimonial
              </h2>
              <p className="max-w-prose text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                {`The resume builder was so easy to use, and the templates are
                fantastic. I got the job!" - Sarah T.`}
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-6 md:py-12">
        <div className="container flex flex-col items-center space-y-4 px-4 md:flex-row md:justify-between md:space-y-0 md:px-6">
          <div className="text-center text-sm text-gray-500 dark:text-gray-400 md:text-base">
            © 2023 ACME Inc. All rights reserved.
          </div>
          <nav className="flex items-center space-x-4 text-sm md:space-x-6">
            <Link className="text-gray-500 underline" href="#">
              Privacy
            </Link>
            <Link className="text-gray-500 underline" href="#">
              Terms
            </Link>
            <Link className="text-gray-500 underline" href="#">
              Contact
            </Link>
          </nav>
        </div>
      </section>
    </div>
  )
}

function GenerateResumeForm() {
  const form = useForm<DownloadPdfSchema>({
    resolver: zodResolver(downloadPdfSchema),
    defaultValues: {}
  })

  return (
    <Form {...form}>
      <section className="w-full py-12 md:py-16 xl:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:items-center lg:gap-12">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Enter your information
              </h2>
              <p className="max-w-prose text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Fill in your details below to get started. We&apos;ll use this
                information to create your personalized resume.
              </p>
            </div>
            <div className="grid gap-4">
              <Input id="name" placeholder="Name" />
              <Input id="email" placeholder="Email" type="email" />
              <Input id="phone" placeholder="Phone" />
              <Input id="linkedin" placeholder="LinkedIn" />
              <Input id="github" placeholder="GitHub" />
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-16 xl:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:items-center lg:gap-12">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Work Experience
              </h2>
              <p className="max-w-prose text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Enter your work experience below, starting with your most recent
                position.
              </p>
            </div>
            <div className="grid gap-4">
              <Input id="company1" placeholder="Company" />
              <Input id="title1" placeholder="Title" />
              <Input id="start1" placeholder="Start Date" type="date" />
              <Input id="end1" placeholder="End Date" type="date" />
              <Input id="description1" placeholder="Description" />
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-16 xl:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:items-center lg:gap-12">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Education
              </h2>
              <p className="max-w-prose text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Enter your education information below, starting with your most
                recent degree.
              </p>
            </div>
            <div className="grid gap-4">
              <Input id="school1" placeholder="School" />
              <Input id="degree1" placeholder="Degree" />
              <Input id="start2" placeholder="Start Date" type="date" />
              <Input id="end2" placeholder="End Date" type="date" />
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-16 xl:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:items-center lg:gap-12">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Skills
              </h2>
              <p className="max-w-prose text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Enter your skills below, separating each one with a comma.
              </p>
            </div>
            <div className="grid gap-4">
              <Input id="skills" placeholder="Skills" />
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-16 xl:py-24">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                Generate your resume
              </h2>
            </div>
            <div className="w-full max-w-sm space-y-2">
              <Button type="submit">Generate Resume</Button>
            </div>
          </div>
        </div>
      </section>
    </Form>
  )
}
