import Head from "next/head"
import { useRouter } from "next/router"
import { Resume } from "~/components/resume"

export default function PdfView() {
  const router = useRouter()

  const expDescCount: Record<string, number> = {}
  const descCount = Array(5).fill(0)

  descCount.forEach((_, i) => {
    if (`desc${i}` in router.query) {
      expDescCount[`desc${i}`] = parseInt(router.query[`desc${i}`] as string)
    }
  })

  if (Object.keys(router.query).length === 0) {
    return null
  }

  const {
    eduCount,
    expCount,
    hasIntro,
    hasPhone,
    hasLinkedIn,
    hasPortfolio,
    hasInterests,
    skillsCount
  } = router.query

  return (
    <>
      <Head>
        <title>gptBJ</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Resume
        expDescCount={expDescCount}
        skillsCount={parseInt(skillsCount as string)}
        educationCount={parseInt(eduCount as string)}
        experienceCount={parseInt(expCount as string)}
        hasIntro={hasIntro === "true"}
        hasPhone={hasPhone === "true"}
        hasLinkedIn={hasLinkedIn === "true"}
        hasPortfolio={hasPortfolio === "true"}
        hasInterests={hasInterests === "true"}
      />
    </>
  )
}
