import Head from "next/head"
import { useRouter } from "next/router"
import { Resume } from "~/components/resume"
import { api } from "~/utils/api"

export default function ResumeView() {
  const router = useRouter()
  const resumeId = router.query.id as string
  const { data, status } = api.resume.readById.useQuery(
    { resumeId },
    { enabled: !!resumeId }
  )

  if (status === "error")
    return (
      <div>
        <Head>
          <title>gptBJ</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {status}
      </div>
    )

  if (status === "success") {
    return (
      <>
        <Head>
          <title>gptBJ</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Resume data={data} />
      </>
    )
  }

  return (
    <>
      <Head>
        <title>gptBJ</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-full place-items-center">Loading...</main>
    </>
  )
}
