import autoprefixer from "autoprefixer"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import postcss from "postcss"
import tailwindcss from "tailwindcss"
import { embedFonts } from "../src/server/modules/profile/embed-fonts"

/**
 * Compiles the print stylesheet into a module the PDF route can import.
 *
 * The print has no origin: `page.setContent` gives Chromium a document that
 * cannot resolve a `<link>` or a `url(/fonts/…)`, so the sheet and every face
 * have to be literal strings inside the markup. The question is only where
 * those strings come from.
 *
 * They used to be read off `.next/static` at request time, which tied printing
 * to a filesystem holding this build's output — true on a container, false on
 * a serverless host that serves static assets from a CDN. Compiling here
 * instead makes the sheet an ordinary import: no filesystem, no build layout to
 * know about, and the half-megabyte of base64 happens once at build time rather
 * than on every cold start.
 *
 * The anti-drift argument for reading the real build output still holds — so
 * this runs the real Tailwind over the real config and the real entrypoint,
 * with the same PostCSS plugins `postcss.config.cjs` gives the Next build.
 * Nothing here is a hand-maintained copy of the utilities the template uses.
 */

const entrypoint = join(process.cwd(), "src", "styles", "global.css")
const output = join(process.cwd(), "src", "generated", "print-css.ts")

async function buildPrintCss() {
  const source = await readFile(entrypoint, "utf8")

  const { css } = await postcss([
    tailwindcss({ config: join(process.cwd(), "tailwind.config.ts") }),
    autoprefixer()
  ]).process(source, { from: entrypoint })

  // `public/fonts` holds the faces, so this resolves against files that exist
  // before the build rather than after it.
  const embedded = await embedFonts(css)

  // `src/generated` is gitignored build output, so a fresh checkout — a CI
  // runner, a Vercel build — has no such directory to write into.
  await mkdir(dirname(output), { recursive: true })

  await writeFile(
    output,
    `// Generated by \`npm run generate:css\` — do not edit.\n` +
      `// The app's compiled Tailwind, with every @font-face embedded as a data URI.\n` +
      `export const printCss = ${JSON.stringify(embedded)}\n`,
    "utf8"
  )

  return { rules: css.length, embedded: embedded.length }
}

void buildPrintCss().then(({ rules, embedded }) => {
  console.log(
    `print-css.ts: ${(rules / 1024).toFixed(0)}KB of CSS, ` +
      `${(embedded / 1024).toFixed(0)}KB with faces embedded.`
  )
})
